dev_addr: 127.0.0.1:8765

nav:
  - Home: index.md
  - About: about.md

plugins:
  - search

repo_url: https://github.com/mozmeao/birdbox-documentation/

site_name: Project Birdbox documentation

site_url: https://mozmeao.github.io/birdbox-documentation/

theme:
  features:
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.ingegrate

  name: material

  language: en

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: blue gray
      accent: green

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: teal

copyright: "© Copyright 2011-2023, Mozilla"